title: "Geo-SfM Course"
logo: ./content/assets/logo.gif
author: Peter Betlem, Nil Rodes and Contributors
copyright: "2023 (CC-BY-NC except where otherwise stated)"

repository:
  url: https://github.com/UNISvalbard/Geo-SfM
  path_to_book: ""  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

html:
  use_issues_button: true
  use_repository_button: true
  extra_navbar: ""
  use_edit_page_button: true
  announcement: 'Found this tutorial helpful? Please participate in the survey (<a href="https://unisvalbard.github.io/Geo-SfM/content/lessons/survey.html">click here</a>) & Star me!        <iframe src="https://ghbtns.com/github-btn.html?user=UNISvalbard&repo=Geo-SfM&type=star&count=true" frameborder="0" scrolling="0" width="150" height="20" title="GitHub"></iframe>'
  comments:
    hypothesis: true

execute:
  execute_notebooks: "auto"

parse:
  myst_extended_syntax: true
  myst_header_anchors: 4

launch_buttons:
  binderhub_url: ""


only_build_toc_files: true

parse:
#  myst_extended_syntax: true
  myst_header_anchors: 4

bibtex_bibfiles:
  - content/lessons/about/zreferences.bib

sphinx:
  config:
    #bibtex_reference_style: author_year
    bibtex_default_style: alpha