title: "Geo-SfM Course"
logo: ./content/assets/logo.gif
author: Peter Betlem and Contributors
copyright: "2022 (CC-BY-NC except where otherwise stated)"

repository:
  url: https://github.com/UNISvalbard/Geo-SfM
  path_to_book: ""  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

html:
  use_issues_button: true
  use_repository_button: false
  extra_navbar: ""
  use_edit_page_button: true
  announcement: "Found this tutorial helpful? Please participate in the survey!"

#  extra_navbar:
#  extra_footer:
#  home_page_in_navbar: Sign up for the <a href="https://www.unis.no/course/ag-222-integrated-geological-methods-from-outcrop-to-geomodel/">UNIS AG222 course</a>

launch_buttons:
  binderhub_url: ""

bibtex_bibfiles:
  - content/lessons/about/zreferences.bib

execute:
  execute_notebooks: "auto"

only_build_toc_files: true

parse:
#  myst_extended_syntax: true
  myst_header_anchors: 4

sphinx:
  config:
    #bibtex_reference_style: author_year
    bibtex_default_style: plain