title: "Geo-SfM Course"
logo: ./content/assets/logo.gif
author: Peter Betlem
copyright: "CC-BY-NC"

repository:
  url: https://github.com/UNISvalbard/Geo-SfM

html:
  use_repository_button: True
  use_issues_button: True
#  extra_navbar:
#  extra_footer:
#  home_page_in_navbar: Sign up for the <a href="https://www.unis.no/course/ag-222-integrated-geological-methods-from-outcrop-to-geomodel/">UNIS AG222 course</a>

launch_buttons:
  binderhub_url: ""

bibtex_bibfiles:
  - content/lessons/about/zreferences.bib

execute:
  execute_notebooks: "auto"

only_build_toc_files: true

parse:
#  myst_extended_syntax: true
  myst_header_anchors: 4
